import Head from "next/head";
import componentList from "../components/data/componentList";

export default function Home() {
  return (
    <>
      <Head>
        <title>React UI Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen space-y-10 bg-slate-50 p-4 text-slate-800 sm:p-6">
        {componentList.map((ui) => (
          <div key={ui.id} className="space-y-4">
            <h3 className="text-3xl font-semibold">{ui.label}</h3>
            <div>{ui.component}</div>
          </div>
        ))}
      </main>
    </>
  );
}
