import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Banner from "../components/Banner";
import Header from "../components/Header";
import AspectRatio from "../components/ratio/AspectRatio";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Cards */}
        <section className="grid grid-cols-1 sm:grid-cols-2 justify-center items-center gap-4 m-4">
          <div className=" bg-zinc-200 text-zinc-800 rounded">
            <AspectRatio ratio="16/9">
              <img
                src="https://www.goodfreephotos.com/albums/united-states/wisconsin/yellowstone-lake-state-park/panoramic-sunset-over-the-ice.jpg"
                className="rounded-t object-cover h-full w-full"
              />
            </AspectRatio>
            <div className="p-5">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.{" "}
            </div>
          </div>
          <div className=" bg-zinc-200 text-zinc-800 rounded">
            <AspectRatio ratio="16/9">
              <div className="rounded-t h-full w-full bg-zinc-400 flex justify-center items-center">
                <h1 className="text-3xl">Some Text</h1>
              </div>
            </AspectRatio>
            <div className="p-5">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.{" "}
            </div>
          </div>
        </section>
        <section className="my-8">
          <FlexWrapper
            justifyContent="justify-around"
            alignItems="items-center"
          >
            <ButtonGroup />
            <ButtonGroup />
          </FlexWrapper>
        </section>
        <section className="my-8">
          <FlexWrapper col>
            <ButtonGroup justifySelf="self-start" />
            <ButtonGroup justifySelf="self-end" />
          </FlexWrapper>
        </section>
        <section className="my-8">
          <FlexWrapper>
            <ButtonGroup />
            <ButtonGroup />
          </FlexWrapper>
        </section>
        <section className="my-8">
          <FlexWrapper alignItems="justify-end">
            <ButtonGroup />
            <ButtonGroup />
          </FlexWrapper>
        </section>
        <section className="my-8">
          <div className="flex rounded max-w-[550px] mx-4 sm:mx-auto">
            <img
              src="https://www.goodfreephotos.com/albums/united-states/wisconsin/yellowstone-lake-state-park/panoramic-sunset-over-the-ice.jpg"
              className="rounded object-cover aspect-video"
            />
            <div className="p-4 flex flex-col gap-2">
              <h3 className="uppercase text-indigo-400 text-lg font-bold">
                Marketing
              </h3>
              <h4 className="font-bold leading-tight">
                Finding customers for your new business
              </h4>
              <p>
                {" "}
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum is simply dummy text of the printing and
                typesetting industry.
              </p>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}

const ButtonGroup = ({ justifySelf, alignSelf }) => {
  return (
    <div className={`inline-flex shadow-lg ${justifySelf} ${alignSelf}`}>
      <button className="bg-zinc-800 py-2 px-4 border-[.2px] border-zinc-700 hover:bg-zinc-700 hover:text-indigo-500 rounded-l">
        Days
      </button>
      <button className="bg-zinc-800 py-2 px-4 border-[.2px] border-zinc-700 hover:bg-zinc-700 hover:text-indigo-500">
        Months
      </button>
      <button className="bg-zinc-800 py-2 px-4 border-[.2px] border-zinc-700 hover:bg-zinc-700 hover:text-indigo-500 rounded-r">
        Years
      </button>
    </div>
  );
};

const FlexWrapper = ({ col, justifyContent, alignItems, children }) => {
  return (
    <div
      className={`${
        col ? "flex-col" : "flex-wrap"
      } flex ${justifyContent} ${alignItems} p-4 bg-zinc-800 max-w-[800px] mx-auto`}
    >
      {children}
    </div>
  );
};

{
  /* <section className="my-8 mx-4">
<nav className="flex justify-evenly">
  <Link
    href="/"
    className="p-2 rounded"
    inactiveClass="hover:text-indigo-500"
    activeClass="bg-zinc-800"
  >
    Home
  </Link>
  <Link
    href="/"
    className="p-2 rounded"
    inactiveClass="hover:text-indigo-500"
    activeClass="bg-zinc-800"
  >
    About
  </Link>
  <Link
    href="/"
    className="p-2 rounded"
    inactiveClass="hover:text-indigo-500"
    activeClass="bg-zinc-800"
  >
    Contact
  </Link>
</nav>
</section>  */
}
